bowl_pose: [0.20, 0.35, 0.75, 0.0, 0.0, 0.0]
pan_pose:  [0.2, 0.02, 0.75, 0.0, 0.0, -2.79]
pan_pour_pose: [0.35, 0.02, 0.94, 3.1416, 0.0, 0.0]

tilt_angle_deg: 180
hold_sec: 3.0
particles: 20
tolerances:
  place_back_xy: 0.03
  place_back_yaw_deg: 8

scene:
  world_yaw_deg: 0 

camera:
  active_view: oblique
  near: 0.05
  far: 5.0
  views:
    oblique:
      xyz: [0.80, 0.25, 1.10]
      rpy: [-55, 0, 160]
      fov_deg: 70
      resolution: [640, 480]
  noise:
    depth_std: 0.0
    drop_prob: 0.0

perception:
  enable: true
  bowl_roi_margin_m: 0.12
  rim_sample_count: 24
  grasp_clearance_m: 0.02
  rim_thickness_m: 0.006

task:
  pan_pour_pose: [0.3, 0.022, 0.94, 3.1416, 0.0, 0.0]
  tilt_angle_deg: 140
  hold_sec: 3.0

  noise:
    depth_std: 0.0
    drop_prob: 0.0

seed: 7